/**

CREATE database spacexeventsdb; 

\c spacexeventsdb

      CREATE TABLE links (          id bigint GENERATED BY DEFAULT AS IDENTITY,          article text NOT NULL,          CONSTRAINT "PK_links" PRIMARY KEY (id)      );

      CREATE TABLE space_x_event (          id bigint GENERATED BY DEFAULT AS IDENTITY,          title text NOT NULL,          event_date_utc timestamp with time zone NOT NULL,          event_date_unix bigint NOT NULL,          details text NOT NULL,          "LinksId" bigint NOT NULL,          CONSTRAINT "PK_space_x_event" PRIMARY KEY (id),          CONSTRAINT "FK_space_x_event_links_LinksId" FOREIGN KEY ("LinksId") REFERENCES links (id) ON DELETE CASCADE      );

INSERT INTO links (article) VALUES ('https://example.com');

INSERT INTO space_x_event (title, event_date_utc, event_date_unix, details, "LinksId") VALUES ('TestTitle', '2023-07-14T19:19:02.031727Z', 1231231231, 'DetailTest', (SELECT id FROM links WHERE article = 'https://example.com'));


**/


